# Generated by Django 3.2.6 on 2021-10-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('meta_data', models.JSONField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
